name: Build and Push Docker Image
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Print PYTHONPATH
        run: echo $PYTHONPATH

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest
        
      - name: Log in to Docker Registry
        uses: docker/login-action@v1
        with:
          username: 02052022
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build Docker image
        run: docker build -t 02052022/example_cicd .

      - name: Push Docker image to Docker Hub
        run: docker push 02052022/example_cicd
